ボウリングのスコア計算プログラム（オブジェクト指向版）を作成
uchihiro04/ruby-practices pull request #10
Opened 2022-08-18 12:31 UTC by uchihiro04

ボウリングのスコア計算プログラム（オブジェクト指向版）を作成しました。
Shotクラス、Frameクラス、Gameクラスの3つに分割しています。

2022-08-24 07:35 UTC, u1tnk requested changes
クラス構成も良いし、概ねシンプルな実装で良いのですが、Gameクラスに偏り過ぎだと思います。
コメントしたところ以外はFrameクラスに処理をいくらか渡す事ができれば良いかと思います 💪

2022-08-24 07:35 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @first_shot = Shot.new(first_mark).score
まず、Shotインスタンスはscoreを出す機能があるので情報量的にFrameはShotクラスのインスタンスを保持するべきです。
また、 変数名として`xxx_shot`とあるとShotクラスのインスタンスかな？というので中身が数値になってしまっているのはよくないというのもあります。

2022-08-24 07:35 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    @frames = []
framesのデータはメソッドを呼んだものを使うのでここで配列だけ初期化しているのは違和感があります。
framesメソッドを initialize_frames等の名前にしてここで呼び出して`@frames`を初期化するのが良いかと思います。

2022-09-06 05:28 UTC, uchihiro04 commented on 07.bowling_object/lib/frame.rb
> +    @first_shot = Shot.new(first_mark).score
Frameクラスのインスタンスの`@first_shot`、`@second_shot``@third_shot`について、Shotクラスのインスタンスを保持するように修正いたしました。

該当commitは[0512a26](https://github.com/uchihiro04/ruby-practices/pull/10/commits/0512a26003812c03ec99d67cc8aa08651a8a650a)です。

2022-09-06 05:30 UTC, uchihiro04 commented on 07.bowling_object/lib/game.rb
> +    @frames = []
Frameクラスのインスタンスにつきましては、Gameクラスのインスタンスメソッドを使って作成する方法から、Frameクラスのクラスメソッドを使って作成する方法に切り替えました。
ご提案いただいた方法とは異なる形になっております。ご確認いただけますと幸いです🙇‍♂️

該当するcommit

2022-09-06 16:19 UTC, u1tnk requested changes
あと一点対応頂ければ大丈夫です！もうちょと 💪

2022-09-06 16:19 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      if frame.strike? && frame.index < 9
ここまで来たら `Frame#score`を作って、bonusも含めたそのFrameのスコアを返してあげて、ここでは足すだけにしましょう！

2022-09-10 08:13 UTC, uchihiro04 commented on 07.bowling_object/lib/game.rb
> +      if frame.strike? && frame.index < 9
Frameクラスに、ボーナス点も含めたフレームのスコアを返すscoreメソッドを作成しました。

該当するcommitは[e688996](https://github.com/uchihiro04/ruby-practices/pull/10/commits/e68899660521fe5454e18dda9b6caf2ff83f47c4)となります。

2022-09-11 16:30 UTC, u1tnk requested changes
もうほんのちょっとです！

最後に必要無くなったアクセサを消してるのはすごく良いですね 👍 
忘れがちだけど大事です。

2022-09-11 16:30 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +  def score(frames, frame)
frame.score(@frames, frame)惜しい！ そのまま移動しちゃったんだと思いますが、`frame.score(@frames, frame)` の frame二つは同じものだと思うので引数で渡す必要無いですよ。
このメソッド内では引数では渡さず、替わりに省略すれば良いです。

ここで `strike?`を呼べば 内部的には `self.strike?`と同義で selfがframeになります。
ちなみに今回無いと思いますが 例えば 、`first_shot = shot`みたいに代入が必要なときは変数と区別できないので省略できなず、 `self.first_shot = shot`みたいにする必要があるのでご注意ください。

2022-09-12 07:45 UTC, uchihiro04 commented on 07.bowling_object/lib/frame.rb
> +  def score(frames, frame)
`frame.score(@Frames, frame)`から引数`frame`を削除し、あわせて`Frame#score`メソッド内の`frame`を削除しました。

該当するcommitは[6c0489f](https://github.com/uchihiro04/ruby-practices/pull/10/commits/6c0489f8c6822e79bf8c13ae09feb9b49321d46c)となります。

2022-09-12 09:56 UTC, u1tnk approved these changes
👍👍👍

2022-09-12 09:56 UTC, u1tnk approved these changes

2022-09-16 07:24 UTC, merged